name: dist-s1-enumerator
dependencies:
 - python>=3.12
 - pip
 - asf_search
 - backoff
 - flake8
 - flake8-blind-except
 - flake8-builtins
 - flake8-import-order
 - geopandas
 - contextily
 - jupyterlab
 - matplotlib
 - numpy
 - pandas
 - pandera
 - pyarrow
 - pytest
 - pytest-cov
 - rasterio
 - requests
 - isort
 - ruff
 - shapely
 - pandas
 - tqdm