name: Unit Tests 

on:
  workflow_dispatch:
    branches:
      - dev
      - main
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  pytest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12", "3.13"]

    steps:
      - uses: actions/checkout@v4

      - uses: mamba-org/provision-with-micromamba@main
        with:
          environment-name: dem-stitcher
          environment-file: environment.yml
          extra-specs: |
            python=${{ matrix.python-version }}


      - name: Pytest in conda environment
        shell: bash -l {0}
        run: |
          python -m pip install .
          pytest . -m 'not integration'