name: Unit Tests 

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  pytest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12", "3.13"]
      fail-fast: false

    steps:
      - uses: actions/checkout@v4

      - uses: mamba-org/setup-micromamba@v2
        with:
          environment-name: dist-s1-enumerator
          environment-file: environment.yml
          extra-specs: |
            python=${{ matrix.python-version }}


      - name: Pytest in conda environment
        shell: bash -l {0}
        run: |
          python -m pip --no-deps install .
          pytest . -m 'not integration'